import type { AppConfig } from './configTypes';

export const appConfig: AppConfig = {
  filters: {
    'dcterms:publisher.skos:prefLabel': {
      type: 'multiselect',
      label: 'Institution',
      icon: 'globe',
      enabled: true,
      meilisearchField: 'dcterms:publisher.skos:prefLabel',
      options: [],
      searchable: true,
      searchPlaceholder: 'Search institutions',
    },
    'dcterms:publisher.isMemberOf.skos:prefLabel': {
      type: 'multiselect',
      label: 'Alliance',
      icon: 'globe',
      enabled: true,
      meilisearchField: 'dcterms:publisher.isMemberOf.skos:prefLabel',
      options: [],
      searchable: true,
      searchPlaceholder: 'Search alliances',
    },
    'dcterms:type.skos:prefLabel': {
      type: 'multiselect',
      label: 'Type',
      icon: 'flag',
      enabled: true,
      meilisearchField: 'dcterms:type.skos:prefLabel',
      options: [],
    },
    'elm:EQFLevel.skos:prefLabel': {
      type: 'multiselect',
      label: 'European Qualifications Framework (EQF) Level',
      icon: 'graduation-cap',
      enabled: true,
      meilisearchField: 'elm:EQFLevel.skos:prefLabel',
      options: [],
    },
    'elm:ISCEDFCode.skos:prefLabel': {
      type: 'multiselect',
      label: 'Field of study',
      icon: 'book',
      enabled: true,
      meilisearchField: 'elm:ISCEDFCode.skos:prefLabel',
      options: [],
    },
    'elm:creditPoint.elm:point': {
      type: 'range',
      label: 'ECTS credits',
      icon: 'globe',
      enabled: true,
      meilisearchField: 'elm:creditPoint.elm:point',
      min: 1,
      max: 30,
      step: 1,
    },
    'dcterms:language.skos:prefLabel': {
      type: 'multiselect',
      label: 'Language',
      icon: 'message-square-more',
      enabled: true,
      meilisearchField: 'dcterms:language.skos:prefLabel',
      options: [],
      searchable: true,
      searchPlaceholder: 'Search languages',
    },
  },

  courseCard: {
    attributesToDisplay: ['id', 'dcterms:title', 'elm:EQFLevel', 'elm:creditPoint.elm:point', 'dcterms:language', 'dcterms:publisher', 'instanceCount' ],
    image: {
      enabled: false,
      aspectRatio: '16:9',
      placeholder: '/assets/images/placeholder-course.svg',
    },
    fields: [
      {
        key: 'dcterms:title',
        type: 'text',
        label: null,
        position: 'header',
        format: '{value}',
        className: 'text-xl font-semibold text-gray-900',
      },
      {
        key: 'dcterms:publisher',
        type: 'text',
        label: null,
        position: 'subheader',
        format: '{value}',
        className: 'text-sm text-gray-600',
      },
      {
        key: 'elm:EQFLevel',
        type: 'badge',
        label: 'Level',
        position: 'badges',
        icon: 'bar-chart',
        format: 'EQF {value}',
      },
      {
        key: 'elm:creditPoint.elm:point',
        type: 'badge',
        label: 'Credits',
        position: 'badges',
        icon: 'book-text',
        format: '{value} ECTS',
      },
      {
        key: 'dcterms:language',
        type: 'badge',
        label: 'Language',
        position: 'badges',
        icon: 'message-square-more',
        format: '{value}',
      },
      {
        key: 'elm:ISCEDFCode',
        type: 'badge',
        label: 'Field of study',
        position: 'badges',
        icon: 'tag',
        format: '{value}',
      },
      {
        // Number of upcoming sessions
        key: 'instanceCount',
        type: 'text',
        label: null,
        position: 'footer',
        format: '{value} upcoming/current offerings',
        className: 'text-xs sm:text-sm text-gray-600',
      },
      {
        // Next upcoming session date — key TBD, will be added later
        key: 'TBD:nextSessionDate',
        type: 'text',
        label: null,
        position: 'footer',
        format: 'Next: {value}',
        className: 'text-xs sm:text-sm text-gray-600',
      },
      {
        // Application/active status — key TBD, will be added later
        key: 'TBD:applicationStatus',
        type: 'badge',
        label: null,
        position: 'footer',
        icon: 'circle',
        format: '{value}',
        valueMap: {
          'true': 'Applications open',
          'false': 'Applications closed',
        },
      },
    ],
  },

  courseDetail: {
    tabs: [
      {
        id: 'basic-info',
        label: 'Overview',
        enabled: true,
        sections: [
          {
            id: 'info-cards',
            title: null,
            layout: 'grid',
            fields: [
              {
                key: 'dcterms:type.skos:prefLabel',
                type: 'info-card',
                label: 'Type',
                icon: 'flag',
                tooltip: 'Type of learning opportunity',
                format: '{value}',
              },
              {
                key: 'elm:creditPoint.elm:point',
                type: 'info-card',
                label: 'Credits',
                icon: 'clock',
                tooltip: 'European Credit Transfer and Accummulation System',
                format: '{value} ECTS',
              },
              {
                key: 'elm:EQFLevel',
                type: 'info-card',
                label: 'Level',
                icon: 'graduation-cap',
                tooltip: 'European Qualifications Framework level',
                format: 'EQF {value}',
              },
              {
                key: 'dcterms:language',
                type: 'info-card',
                label: 'Language',
                icon: 'globe',
                tooltip: 'Language of instruction',
                format: '{value}',
              },
              {
                key: 'version',
                type: 'info-card',
                label: 'Version',
                icon: 'git-branch',
                tooltip: 'Course version',
                format: '{value}',
              },
              {
                key: 'ql:isActive',
                type: 'info-card',
                label: 'Status',
                icon: 'check-circle',
                tooltip: 'Course active status',
                format: '{value}',
                valueMap: {
                  'true': 'Active',
                  'false': 'Inactive',
                },
              },
            ],
          },
          {
            id: 'main-info',
            title: null,
            layout: 'list',
            fields: [
              {
                key: 'adms:identifier',
                type: 'list',
                label: 'IDENTIFIERS',
                tooltip: 'Course identifier used in the provider internal system',
                format: 'bullet',
                icon: 'check-circle',
              },
              {
                key: 'dcterms:description',
                type: 'text',
                label: 'DESCRIPTION',
                tooltip: 'Course description',
                format: '{value}',
              },
              {
                key: 'elm:ISCEDFCode',
                type: 'link',
                label: 'ISCED CODE',
                tooltip: 'International Standard Classification of Education',
                format: '{value}',
              },
              {
                key: 'elm:learningOutcome',
                type: 'list',
                label: 'LEARNING OUTCOMES',
                tooltip: 'Detailed learning outcomes',
                format: 'bullet',
                icon: 'check-circle',
              },
              {
                key: 'elm:learningOutcomeSummary.elm:noteLiteral',
                type: 'text',
                label: 'LEARNING OUTCOMES',
                tooltip: 'Detailed learning outcomes',
                format: '{value}',
              },
              {
                key: 'foaf:homepage.elm:contentUrl',
                type: 'link',
                label: 'Link',
                icon: 'external-link',
                format: '{value}',
              },
            ],
          },
        ],
      },
      {
        id: 'offerings',
        label: 'Offerings',
        enabled: true,
        sections: [
          {
            id: 'offerings-list',
            title: null,
            layout: 'list',
            fields: [
              {
                key: 'elm:learningOpportunity',
                type: 'offerings',
                label: 'Offerings',
                titleKey: 'dcterms:title',
                details: [
                  {
                    label: 'When',
                    type: 'date-range',
                    icon: 'calendar',
                    keys: {
                      label: 'dcterms:temporal.dcterms:PeriodOfTime.skos:prefLabel',
                      from: 'dcterms:temporal.elm:startDate.@value',
                      to: 'dcterms:temporal.elm:endDate.@value',
                    },
                  },
                  {
                    label: 'Language',
                    type: 'text',
                    icon: 'message-square-more',
                    key: 'elm:defaultLanguage.skos:prefLabel',
                  },
                  {
                    label: 'Mode',
                    type: 'text',
                    icon: 'monitor',
                    key: 'elm:mode.skos:prefLabel',
                  },
                  {
                    label: 'Application deadline',
                    type: 'text',
                    icon: 'clock',
                    key: 'elm:applicationDeadline',
                  },
                  {
                    label: 'Provided by',
                    type: 'text',
                    icon: 'building',
                    key: 'elm:providedBy.skos:prefLabel',
                  },
                  {
                    label: 'Link',
                    type: 'link',
                    icon: 'external-link',
                    key: 'foaf:homepage',
                  },
                ],
                noteKey: 'dcterms:description',
                noteLabel: 'Description',
              },
            ],
          },
        ],
      },
      {
        id: 'provider',
        label: 'Provider',
        enabled: true,
        sections: [
          {
            id: 'provider-details',
            title: null,
            layout: 'list',
            fields: [
              {
                key: 'dcterms:publisher',
                type: 'link',
                label: 'PROVIDER',
                tooltip: 'Education institution publishing this course',
                format: '{value}',
              },
              {
                key: 'dcterms:publisher.regorg:legalName',
                type: 'link',
                label: 'OFFICIAL NAME',
                format: '{value}',
              },
              {
                key: 'dcterms:publisher.adms:identifier',
                type: 'list',
                label: 'IDENTIFIERS',
                tooltip: 'Identifiers of this provider',
                format: 'bullet',
                icon: 'check-circle',
              },
              {
                key: 'dcterms:publisher.elm:location',
                type: 'list',
                label: 'LOCATIONS',
                tooltip: 'Physical sites of this provider',
                format: 'bullet',
                icon: 'check-circle',
              },
              {
                key: 'dcterms:publisher.foaf:homepage.elm:contentUrl',
                type: 'link',
                label: 'Website',
                icon: 'external-link',
                format: '{value}',
              },
            ],
          },
        ],
      },
      {
        id: 'metadata',
        label: 'Technical info',
        enabled: true,
        sections: [
          {
            id: 'identifiers',
            title: null,
            layout: 'list',
            fields: [
              {
                key: 'uri',
                type: 'link',
                label: 'URI',
                tooltip: 'URI of this course, by data provider or generated by the aggregator',
                format: '{value}',
              },
              {
                key: 'id',
                type: 'text',
                label: 'UUID',
                tooltip: 'Unique identifier',
                format: '{value}',
              },
              {
                key: 'version',
                type: 'text',
                label: 'Version',
                tooltip: 'Version number/identifier assigned by the provider',
                format: '{value}',
              },
              {
                key: 'ingestedAt',
                type: 'text',
                label: 'Last updated',
                tooltip: 'Timestamp when this course data was last fetched from the provider',
                format: '{value}',
              },
            ],
          },
        ],
      },
    ],
  },

  theme: {
    colors: {
      primary: '#0b223b',
      primaryHover: '#0a1d31',
      secondary: '#1c64f2',
      secondaryHover: '#1e5cdb',
      background: '#f9fafb',
      link: '#2563eb',
    },
    logo: {
      url: '/assets/images/logo.png',
      name: 'QualityLink',
    },
    fonts: {
      primary: 'Inter, system-ui, -apple-system, sans-serif',
    },
    layout: {
      maxWidth: '1240px',
      cardAspectRatio: '16:9',
      gridColumns: {
        mobile: 1,
        tablet: 2,
        desktop: 3,
      },
    },
  },

  formats: {
    currency: {
      template: '{value} {currency}',
      defaultCurrency: 'EUR',
    },
    ects: {
      template: '{value} ECTS',
      suffix: 'ECTS',
    },
    eqfLevel: {
      template: 'EQF {value}',
      prefix: 'EQF ',
    },
    percentage: {
      template: '{value}%',
      decimals: 0,
    },
    date: {
      template: '{value}',
      format: 'YYYY-MM-DD',
      locale: 'en-US',
    },
  },

  icons: {
    deliveryMode: {
      Online: 'monitor',
      'In person': 'users',
      Blended: 'monitor-smartphone',
    },
    ects: 'clock',
    eqfLevel: 'graduation-cap',
    language: 'globe',
    location: 'map-pin',
    price: 'euro',
    calendar: 'calendar',
    provider: 'building',
    skills: 'award',
    assessment: 'clipboard-check',
  },
};
